//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace banking
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class banking_dbEntities : DbContext
    {
        public banking_dbEntities()
            : base("name=banking_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admin_Table> Admin_Table { get; set; }
        public DbSet<debit> debit { get; set; }
        public DbSet<deposit> deposit { get; set; }
        public DbSet<employee> employee { get; set; }
        public DbSet<FD> FD { get; set; }
        public DbSet<Transfer> Transfer { get; set; }
        public DbSet<userAccount> userAccount { get; set; }
        public DbSet<userTable> userTable { get; set; }
    }
}
